In [14]:
import pandas as pd
import numpy as np
data = np.arange(1,36).reshape(7,5)
print(data)
df = pd.DataFrame(data,index=["A","B","C","D","E","F","G"])
print(df)
df.to_csv('data1.csv')
d = pd.read_csv('data1.csv')
d.head()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
    0   1   2   3   4
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25
F  26  27  28  29  30
G  31  32  33  34  35


,Unnamed: 0,0,1,2,3,4
0,A,1,2,3,4,5
1,B,6,7,8,9,10
2,C,11,12,13,14,15
3,D,16,17,18,19,20
4,E,21,22,23,24,25
